# Configuración del Servidor (Render asigna el puerto automáticamente)
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Variables de Seguridad y API de películas

jwt.secret=${JWT_SECRET}
jwt.expiration-time=3600000
tmdb.api.token=${TMDB_API_KEY}

permit.all.resources=/index.html, /favicon.ico, /media/**, /**/*.js, /**/*.css
permit.all.paths=/login, /error