server.port=8080
server.servlet.context-path=/api

logging.level.org.springframework.security=TRACE
logging.level.root=INFO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

tmdb.api.token=${TMDB_API_KEY}

jwt.secret=${JWT_SECRET}

server.error.include-message=always

permit.all.resources=/index.html, /favicon.ico, /media/**, /**/*.js, /**/*.css, /api-docs/swagger.yaml
permit.all.paths=/login, /error, /swagger-ui/**, /api-docs, /v3/api-docs/**, /swagger-ui.html, /api/swagger-ui/**, /api-docs/swagger-config

# 1. Ruta para entrar a la web de Swagger (puedes poner la que quieras)
springdoc.swagger-ui.path=/swagger-ui.html

# 2. El secreto: dile a la web de Swagger que lea TU archivo descargable
springdoc.swagger-ui.url=/api-docs/swagger.yaml

# Habilitamos el escaneo (pero no te preocupes, no lo usaremos)
springdoc.api-docs.enabled=true