# Configuracion del Servidor (Render asigna el puerto automaticamente)
server.port=${PORT:8080}
server.servlet.context-path=/api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 1. Habilitar la inicializacion de datos
#spring.sql.init.mode=always

# 2. Listar los archivos en el orden exacto en que deben ejecutarse (separados por comas)
#spring.sql.init.data-locations=classpath:sql/inserts_premio.sql,classpath:sql/inserts_categorias.sql,classpath:sql/inserts_categoriaspremios.sql,classpath:sql/inserts_movie.sql,classpath:sql/inserts_ganador.sql,classpath:sql/alter_listamovies.sql

# 3. Asegurar que Hibernate cree las tablas ANTES de que se ejecuten estos scripts
#spring.jpa.defer-datasource-initialization=true

# Variables de Seguridad y API de peliculas

jwt.secret=${JWT_SECRET}

tmdb.api.token=${TMDB_API_KEY}

permit.all.resources=/index.html, /favicon.ico, /media/**, /**/*.js, /**/*.css
permit.all.paths=/login, /error