server.port=8080
server.servlet.context-path=/api

logging.level.org.springframework.security=TRACE
logging.level.root=INFO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.OracleLegacyDialect
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME_TEST}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_TEST}

tmdb.api.token=${TMDB_API_KEY}

jwt.secret=${JWT_SECRET}

server.error.include-message=always

permit.all.resources=/index.html, /favicon.ico, /media/**, /**/*.js, /**/*.css
permit.all.paths=/login, /error, /testing/reset

captcha.secret.key=${CAPTCHA_KEY}
