Insert into CATEGORIA (ID,NOMBRE) values ('1','Mejor película');
Insert into CATEGORIA (ID,NOMBRE) values ('2','Actor revelación');
Insert into CATEGORIA (ID,NOMBRE) values ('3','Dirección');
Insert into CATEGORIA (ID,NOMBRE) values ('4','Música original');
Insert into CATEGORIA (ID,NOMBRE) values ('5','Dirección de producción');
Insert into CATEGORIA (ID,NOMBRE) values ('6','Efectos especiales');
Insert into CATEGORIA (ID,NOMBRE) values ('7','Sonido');
Insert into CATEGORIA (ID,NOMBRE) values ('8','Maquillaje y peluquería');
Insert into CATEGORIA (ID,NOMBRE) values ('9','Dirección de fotografía');
Insert into CATEGORIA (ID,NOMBRE) values ('10','Diseño de vestuario');
Insert into CATEGORIA (ID,NOMBRE) values ('11','Montaje');
Insert into CATEGORIA (ID,NOMBRE) values ('12','Dirección artística');
Insert into CATEGORIA (ID,NOMBRE) values ('13','Actriz rebelación');
Insert into CATEGORIA (ID,NOMBRE) values ('14','Actriz reparto');
Insert into CATEGORIA (ID,NOMBRE) values ('15','Dirección novel');
Insert into CATEGORIA (ID,NOMBRE) values ('16','Película Iberoamericana');
Insert into CATEGORIA (ID,NOMBRE) values ('17','Actriz protagonista');
Insert into CATEGORIA (ID,NOMBRE) values ('18','Actor protagonista');
Insert into CATEGORIA (ID,NOMBRE) values ('19','Actor reparto');
Insert into CATEGORIA (ID,NOMBRE) values ('20','Película de animación');
Insert into CATEGORIA (ID,NOMBRE) values ('21','Cortometraje de ficción');
Insert into CATEGORIA (ID,NOMBRE) values ('22','Cortometraje documental');
Insert into CATEGORIA (ID,NOMBRE) values ('23','Cortometraje de animación');
Insert into CATEGORIA (ID,NOMBRE) values ('24','Guión adaptado');
Insert into CATEGORIA (ID,NOMBRE) values ('25','Guión original');
Insert into CATEGORIA (ID,NOMBRE) values ('26','Película europea');
Insert into CATEGORIA (ID,NOMBRE) values ('27','Película documental');