@startuml
skinparam actorStyle awesome
left to right direction

actor "User" as U
actor "Admin" as A

rectangle "Todo Cine System" {

    package "User Management" {
        U -- (Register/Login)
        U -- (View Profile)
        U -- (Update Profile)
    }

    package "Movie Catalog" {
        U -- (Search Movies)
        U -- (View Movie Details)
        U -- (List Movies Playing in Theaters)
        (List Movies Playing in Theaters) ..> (Filter by Region) : <<extend>>
    }

    package "Social & Interactions" {
        U -- (Mark as Favorite)
        U -- (Mark as Watched)
        U -- (Rate Movie)
        U -- (View Personal Favorite)
        (View Personal Favorite) ..> (Filter by Watched/Rated) : <<extend>>

    }

    package "Awards & History" {
        U -- (View Winners by Year)
        A -- (Insert New Winner)
    }

    package "Custom lists" {
        U -- (Create list)
        U -- (Edit list)
        U -- (View owned lists)
        U -- (View public lists)
        U -- (Delete list)
        U -- (Add movie to list)
        U -- (Remove movie from list)
        U -- (Share your opinion about a list)
        U -- (View opinions about a list)
    }
}

' Inheritance: Admin can do everything a User can
A --|> U


@endum