name: Generador de Diagramas UML

# El robot se activará cada vez que hagas un push a la rama 'main'
on:
  push:
    branches: [ "master" ]

jobs:
  render-uml:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código de tu repositorio en la máquina virtual
    - name: Descargar repositorio
      uses: actions/checkout@v4

    # 2. NUEVA ACTION: Corre el motor oficial de PlantUML
    - name: Renderizar archivos PlantUML
      uses: plantuml/plantuml-github-action@main
      with:
        args: -v -tpng src/main/resources/uml/*.puml # Busca todos los .puml de la carpeta diagramas

    # 3. El robot guarda las imágenes generadas de vuelta en tu repositorio
    - name: Subir imágenes generadas al repositorio
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add src/main/resources/uml/*.png
        # Solo hace commit si realmente cambiaron los diagramas para evitar errores
        git diff-index --quiet HEAD || git commit -m "Bot: Actualización automática de diagramas UML [skip ci]"
        git push
